# Generated by Django 4.2.7 on 2024-03-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AttendanceApp.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AttendanceApp.student')),
            ],
        ),
    ]
