# Generated by Django 4.2.7 on 2024-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0007_studymaterial_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
